import type { NextPage } from "next";
import Head from "next/head";
import styles from "../../styles/Home.module.css";

const productsTest = [{ id: "teste1" }, { id: "teste2" }, { id: "teste5" }];

const Home: NextPage<{ products?: { id: string }[] }> = ({ products }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>products {products?.length}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>products {products?.length}</h1>
      </main>
    </div>
  );
};

// SSG - Static Site Generating
export async function getStaticProps() {
  // request api here and return in props for component (updated only each time build)

  // revalidate -> seconds, ISR = Incremental Static Regeneration (work with Vercel)

  return { props: { products: productsTest }, revalidate: 1000 };
}

export async function getStaticPaths() {
  // request api here for get data for pages

  // fallback:
  // false -> return 404, if not builded with this data param
  // blocking -> return white page while request and build page
  // true -> return reload page while request and build page

  return {
    paths: productsTest.map((product) => ({ params: { id: product.id } })),
    fallback: false,
  };
}

export default Home;
