import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Home: NextPage<{ test?: string }> = ({ test }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App {test}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a> {test}
        </h1>
      </main>
    </div>
  );
};

// SSR - Server Side Rendering
export async function getServerSideProps() {
  // request api here and return in props for component (dinamic)

  return { props: { test: "hi" } };
}

export default Home;
